### PR TITLE
Prepare next release

### PR DESCRIPTION
**Pull request by johnraz**
Some things that need to be done before develop is ready:

- [x] Changelog should be updated
- [ ] Base on the changelog update a version should be promoted
- [x] A task to generate the documentation and publish the github page should be put in place
- [x] Access to the pypi registry should be gained

Keep this PR in draft until the above are done

@James1345 @giovannicimolin

### CODE REVIEW

**Comment by giovannicimolin** [comment]
Implemented the CI job to automatically push documentation updates: https://github.com/jazzband/django-rest-knox/pull/343

**Comment by giovannicimolin** [comment]
Also, referencing the discussion on https://github.com/jazzband/django-rest-knox/issues/304:
1. Jazzband was invited to be a maintainer of this repo on Pypi.
2. https://github.com/jazzband/django-rest-knox/issues/304#issuecomment-2092529048: Let's use `develop` as the new main branch and use tags for Pypi versions.

**Comment by johnraz** [comment]
In the scope of this new release I'd like to suggest that we maintain a changelog and require every PR to add content to it.

In order to make the process as streamlined and conflict free as possible, I'd like to suggest the following tool -> https://changie.dev/ - thoughts?

**Comment by giovannicimolin** [comment]
@johnraz Oh, that's a neat tool! 

I need to catch up the changelog with the merges though, there's quite a few things that were merged but are missing from there (all minor things or fixes though).
We still haven't got Pypi access, so I'm thinking of creating a mirror repo just to unblock releases until that is solved.

**Comment by vasilistotskas** [comment]
Any updates on this?

**Comment by johnraz** [comment]
> Any updates on this?

The fact that the MR is not progressing should give you a hint…

We are still trying to gain shared access to the pypi repository and need to find some time to address the points above.

**Comment by max-wittig** [comment]
@johnraz Hi! Seems like we didn't get updates for 2 years now. We would really like to have more consistent updates as its a critical component. Is there anything that we can support here?

**Comment by James1345** [comment]
@johnraz Jazzband has been invited to the pypi repo, is there anything else needed from me to get that handed over so this can progress without me?

**Comment by johnraz** [comment]
@max-wittig the only supportive thing to do at this stage is to be patient.

@James1345 that’s awesome, I’m not sure if full access to the github repo was already given or not to jazzband but if that’s the case than nothing else should be needed! Thanks a lot for taking the time.

**Comment by giovannicimolin** [comment]
@James1345 Thanks for the Pypi access!

@johnraz I now have maintainer access on Pypi and can deploy new versions. 
We now need to do some cleanup, update the changelog and we'll be good to deploy a new version.

**Comment by johnraz** [comment]
Awesome I'll try to free up some time in the coming days - if you don't see me move feel free to take action too 😉

**Comment by johnraz** [comment]
@giovannicimolin  please see https://github.com/jazzband/django-rest-knox/pull/355 it adds the changelog and should fix the conflict...

**Comment by giovannicimolin** [comment]
@johnraz Nice! I reviewed and merged the PR.
We missed changing the version in `setup.py` though. 

I can do that when figuring out how to release a new version this week though!

**Review by giovannicimolin — APPROVED** [review]
:+1: 

Looks good, let's get this release going.

**Comment by vasilistotskas** [comment]
pip version 5?

**Comment by max-wittig** [comment]
Thanks for the release! I love it that you put the warning right on top where people can see them!

**Pull request merged**
